---

- name: install dependencies
  apt:
    name: '{{ item }}'
    state: 'present'
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - git
    - python3
    - openssl
    - libssl-dev
    - libacl1-dev
    - python3-dev
    - python3-setuptools

- name: install pip3
  easy_install:
    executable: 'easy_install3'
    name: 'pip'

- name: install attic dependencies through pip
  pip:
    executable: 'pip3'
    name: '{{ item }}'
  with_items:
    - 'msgpack-python'
    - 'cython'

- set_fact:
    attic_dependency_pkgs: '{{ attic_dependency_pkgs | difference(["python3-msgpack","cython3"]) }}'